### ISSUE TITLE
Audioservice ignores wav-files

### ISSUE THREAD

**Issue by cengels9** [Particle1904/CSharpSoundboard#1]
I don't know if you care, and this is a minor thing, but the Audioservice class only searches for mp3-files.

I fixed that by replacing this line

https://github.com/Particle1904/CSharpSoundboard/blob/26bfafca38504a2596bf8268470687e2835160ca/Soundboard.Lib/Services/AudioManagerService.cs#L157

by 

```
string[] soundFiles = new []{"*.mp3", "*.wav"}.SelectMany(e => Directory.GetFiles(inputFolderPath, e)).ToArray();
```

**Comment by Particle1904** [comment]
Oh yeah, it was intentional since all the audio files I usually have are edited so they end up being .mp3's.
Feel free to make a PR if you want.
